### PR TITLE
Feature/28/60 Performance test example with workflow

### PR DESCRIPTION
**Pull request by cpeeyush**
## What this PR changes/adds

- Adds simple performance test example by reusing existing test.
- Adds performancetests.yml workflow to run nightly and can be triggered manually as well.
- Update documentation to adds a section about performance tests.

## Why it does that

- Base work for future performance tests.

## Linked Issue(s)

Relates to #60 

## Checklist

- [ ] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by cpeeyush** [comment]
Successful performance test run https://github.com/agera-edc/DataSpaceConnector/actions/runs/2065607095

**Review by algattik — APPROVED** [review]
I guess it was intentional not to allow the user to specify the parameter values when running the workflow manually?

**Review by chrislomonico — APPROVED** [review]

**Comment by cpeeyush** [comment]
> I guess it was intentional not to allow the user to specify the parameter values when running the workflow manually?

I didn't think of that. But it can be a good idea, I will take a look.

**Comment by algattik** [comment]
> I didn't think of that. But it can be a good idea, I will take a look.

not strictly required since the issue doesn't demand it, but would be a nice to have.

**Comment by cpeeyush** [comment]
Successful Manual trigger run https://github.com/agera-edc/DataSpaceConnector/actions/runs/2069444491

**Pull request merged**
